### ISSUE TITLE
Can you provide a image of results?

### ISSUE THREAD

**Issue by liaoksn** [AndreaMelle/pointBasedRendering#1]
I'm trying to follow your program to learn something about point based rendering. But there is only a red point in my screen. I want to know if this program worked. Can you leave a image of your result, then i can know more about this program?

**Comment by liaoksn** [comment]
Finally I found this problem was canused by the difference in the version of glm. Since the version of my glm is 0.9.9, i must initialize mat4 with glm::mat4 model = glm::mat4(1.0f), then everything goes well

**Comment by liaoksn** [comment]
thanks for your program

**Comment by AndreaMelle** [comment]
I’m sorry, this repo is 7 years old. This was just the first commit of some personal project I never followed up on, so this code does mostly nothing.
